### ISSUE TITLE
suggestion: change phase from verify to validate

### ISSUE THREAD

**Issue by shaunthegeek** [tomasbjerre/violations-maven-plugin#2]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/4971414/189529547-dfd32e19-b7a9-4857-84f1-1193feabbd53.png">

https://github.com/tomasbjerre/violations-maven-plugin/blob/master/violations-maven-plugin-example/pom.xml#L23

now the docs tell us to using `mvn verify`, but unit test and it test are in `verify` too, it will cause 2 problem:

1. `violations-maven-plugin` can not run alone, always run with test, the speed is slow.
2. if test failed and stop, this plugin `violations-maven-plugin` will not run, so we can not get a report.

Demo: https://github.com/WebGoat/WebGoat

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/4971414/189530502-f0af564e-48da-453e-a0ff-29a39c74e1e8.png">

<img width="978" alt="image" src="https://user-images.githubusercontent.com/4971414/189530597-c5b73d77-e303-4fe2-9510-359611f15c1e.png">

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/4971414/189530646-a8a833ac-da68-4dd5-92df-54b96b24fa09.png">

if we want `lint and collect report` first, if lint success, run `test and collect report`, this plugin can not do it:

```
image: bellsoft/liberica-openjdk-debian:17

stages:
  - lint
  - test
  - build

lint_and_report:
  stage: lint
  script:
    - ./mvnw checkstyle:check
    - ./mvnw verify # convert format after test, so it failed
  artifacts:
    when: always
    reports:
      codequality: gl-code-quality-report.json.json

test_and_report:
  stage: test
  script:
    - ./mvnw verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

build_java:
  stage: build
  script:
    - ./mvnw package -Dmaven.test.skip=true
```
